### ISSUE TITLE
Support RC versions

### ISSUE THREAD

**Issue by sellmair** [LouisCAD/CompleteKotlin#5]
When applied to 1.5.30-RC:

```
Caused by: java.lang.IllegalStateException: Unknown meta version: RC
        at com.louiscad.complete_kotlin.internal.MetaVersion$Companion.findAppropriate(MetaVersion.kt:20)
        at com.louiscad.complete_kotlin.internal.CompilerVersion$Companion.fromString(CompilerVersion.kt:39)
        at com.louiscad.complete_kotlin.internal.CompilerVersion$Companion.current(CompilerVersion.kt:26)
        at com.louiscad.complete_kotlin.internal.TargetsHandlerKt.completePlatformKlibsIfNeeded(TargetsHandler.kt:24)
        at com.louiscad.complete_kotlin.CompleteKotlinPlugin$setup$1$1$1.execute(CompleteKotlinPlugin.kt:48)
        at com.louiscad.complete_kotlin.CompleteKotlinPlugin$setup$1$1$1.execute(CompleteKotlinPlugin.kt:16)
        at org.gradle.configuration.internal.DefaultUserCodeApplicationContext$CurrentApplication$1.execute(DefaultUserCodeApplicationContext.java:100)
        at org.gradle.api.internal.DefaultCollectionCallbackActionDecorator$BuildOperationEmittingAction$1.run(DefaultCollectionCallbackActionDecorator.java:95)

```

**Comment by LouisCAD** [comment]
Curious, I copied that code from Kotlin repo and I'm pretty sure it was supporting RC versions 🤔

If you have any idea, please let me know. I plan to investigate later this week.

**Comment by Syer10** [comment]
This has RC1 and RC2, but not a regular RC.
https://github.com/LouisCAD/CompleteKotlin/blob/main/plugin/src/main/kotlin/com/louiscad/complete_kotlin/internal/MetaVersion.kt#L7

**Comment by LouisCAD** [comment]
@sellmair Did Kotlin/Native distribution versioning change recently?

**Comment by sellmair** [comment]
> @sellmair Did Kotlin/Native distribution versioning change recently?

🤷 

Where did you copy this code from the Kotlin repo?

**Comment by LouisCAD** [comment]
From this file, but I see that it changed since then: https://github.com/JetBrains/kotlin/blob/1.5.30/compiler/util-io/src/org/jetbrains/kotlin/konan/CompilerVersion.kt

I need to setup a GitHub Action in this repo that will let me know when one of these files changes on master.

Now that we can run Kotlin scripts out of the box in the runners, it might be a good time to do it :)

**Comment by LouisCAD** [comment]
New year resolution, fix CompleteKotlin, and enable myself to fix it in time if Kotlin changes anything that clashes with CompleteKotlin.

**Comment by LouisCAD** [comment]
RC and RC2 versions with the new versioning scheme are now supported in 1.1.0
